---
# Based on calamares-settings-debian; autologin into Hyprland for the installed user.

userGroup:       users
defaultGroups:
    - cdrom
    - floppy
    - sudo
    - audio
    - dip
    - video
    - plugdev
    - netdev
    - lpadmin
    - scanner
    - bluetooth
autologinGroup:  autologin
sudoersGroup:    sudo
setRootPassword: false

displayAutologin: true
doAutologin:      true

passwordRequirements:
    minLength: 1
    maxLength: -1
allowWeakPasswords: true
allowWeakPasswordsDefault: true
