[editor]
use_default_font = false
editor_font = "Cascadia Code 12"
scheme = "Adwaita-dark"
create_backup_copy = false
auto_save = false
auto_save_interval = 10
max_undo_actions = 2000
wrap_mode = "word"
tabs_size = 8
insert_spaces = false
auto_indent = false
display_line_numbers = false
highlight_current_line = false
bracket_matching = false
display_right_margin = false
right_margin_position = 80
smart_home_end = "after"
restore_cursor_position = true
syntax_highlighting = true
search_highlighting = true
ensure_trailing_newline = true
backup_copy_extension = "~"

[ui]
toolbar_visible = false
notebook_show_tabs_mode = "always"
statusbar_visible = true
side_panel_visible = true
bottom_panel_visible = true
max_recents = 5

[print]
print_syntax_highlighting = true
print_header = true
print_wrap_mode = "word"
print_line_numbers = 0
print_font_body = "Cascadia Code 9"
print_font_header = "Sans 11"
print_font_numbers = "Sans 8"

[encodings]
auto_detected = [
    "UTF-8",
    "CURRENT",
    "ISO-8859-15",
    "UTF-16",
]
shown_in_menu = ["ISO-8859-15"]

[plugins]
active_plugins = [
    "docinfo",
    "modelines",
    "filebrowser",
    "filesearch",
    "markdown",
    "spell",
    "time",
    "todolist",
    "terminal",
]

[state]
window_width = 650
window_height = 500
side_panel_size = 267
bottom_panel_size = 667
side_panel_page = "filebrowser"
search_history = []
replace_history = []
recent_files = []

[session]
restore_on_startup = true
open_files = []
