"""Python bindings for the shared GTK-Apps theme suite."""

from .gtk_theme import (  # noqa: F401
    Profile,
    append_profile_menu,
    apply_adw_color_scheme,
    apply_chrome,
    apply_chrome_gtk3,
    attach_profile_menu,
    attach_profile_menu_gtk3,
    all_profiles,
    build_profile_only_menu,
    builtin_profiles,
    chrome_css,
    default_profile,
    ensure_neuron_daemon,
    install_about_action,
    install_open_theme_editor_action,
    integrate_profile_menu,
    launch_theme_editor,
    load_profile,
    load_theme_id,
    meld_chunk_colours,
    profile_by_id,
    resolve_sourceview_scheme,
    save_theme_id,
    select_theme,
    show_about_dialog,
    sourceview_scheme_candidates,
    sync_hyprbars,
    sync_desktop_theme,
    sync_shell_chrome,
    watch_theme,
)
